config/routes.rb
Rails.application.routes.draw do

  namespace 'api' do
    namespace 'v1' do
      resources :categories
      resources :posts
      resources :confirmations, only: [:create] 
      resources :sessions, only: [:create, :destroy_user] do
        get :destroy_user, on: :collection
      end
    end
  end

  root 'home#index'
  get 'home/index'
  resources :posts
  # devise_for :users, controllers: { confirmations: 'confirmations', sessions: "user/sessions" }
  devise_for :users, :controllers => {:sessions => "sessions"}
  resources :users
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # mount V1::User::Registrations => '/api'
end

app/models/category.rb
class Category < ApplicationRecord; end

app/controllers/api/v1/categories_controller.rb
module Api
	module V1
		class CategoriesController < BaseController
      # before_action :authenticate!
  		before_action :set_category, only: [:show, :edit, :update, :destroy]
  # GET /categorys
  # GET /categorys.json
  def index
    categories = Category.all
    render json: {status: 'SUCCESS', message: 'Loaded Categories', data: categories},status: :ok
  end

  # GET /categorys/1
  # GET /categorys/1.json
  def show
    category = Category.find_by_id(params[:id])
    post = Post.where(category: category.id) #all posts associated with the category
    render json: {status: 'SUCCESS', message: 'Loaded Category', data: category},status: :ok 
  end

  # GET /categorys/new
  def new
    category = Category.new
  end

  # category /categorys
  # category /categorys.json
  def create
    category = Category.new(category_params)
      if category.save
        render json: {status: 'SUCCESS', message: 'Category Saved', data: category},status: :ok 
      else
        render json: {status: 'ERRORS', errors: 'Category Not Saved', data: category.errors},status: :unprocessable_entity 
      end
  end

  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.permit(:category_title, :category_description)
    end
end

	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  # GET /categorys
  # GET /categorys.json
  def index
    @categories = Category.all
  end

  # GET /categorys/1
  # GET /categorys/1.json
  def show
    @posts = Post.where(category: @category.id) #all posts associated with the category
  end

  # GET /categorys/new
  def new
    @category = Category.new
    
  end

  # GET /categorys/1/edit
  def edit
  end

  # category /categorys
  # category /categorys.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categorys/1
  # PATCH/PUT /categorys/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_title, :category_description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :category_title, :required => true %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :category_description, :required => true %>
  </div>
  
   
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<%= link_to 'New Category', new_category_path %>
<!-- secondary Navigation-->
<div class="sec-nav admin-sec-nav">
  <div class="container">
    <h4>MANAGE CATEGORIES</h4>
  </div>
</div>

        <div>
            <table cellspacing="0" width="100%">
              <thead>
                  <tr>
                    <th>
                      Category Title </th>
                    <th>
                      Category Description</th>
                      <th>
                      Actions</th>
                  </tr>
              </thead>
              <tbody>
            <% if @categories.present? %>
              <% @categories.each do |category| %>
              <tr>
              <td><%= category.category_title %></td>
              <td><%= category.category_description %></td>
              <td class="actioncell pb10">
              <%= link_to 'show', category_path(category) %>
              <%= link_to 'edit', edit_category_path(category) %>
              <%#= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
             <% end %>
            <% else %>
              <tr>
              <td colspan="6" class="center">No categries found.</td>
              </tr>
            <% end %>
              </tbody>
            </table>
    </div>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>title:</strong>
  <%= @category.category_title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.category_description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<div class="sec-nav admin-sec-nav">
  <div class="container">
    <h4>POSTS ASOCIATED WITH THE CATEGORY</h4>
  </div>
</div>

        <div>
            <table cellspacing="0" width="100%">
              <thead>
                  <tr>
                    <th>
                      Post Title </th>
                    <th>
                      Post Description</th>
                  </tr>
              </thead>
              <tbody>
            <% if @posts.present? %>
              <% @posts.each do |post| %>
              <tr>
              <td><%= post.title %></td>
              <td><%= post.description %></td>
              </tr>
             <% end %>
            <% else %>
              <tr>
              <td colspan="6" class="center">No posts found associated with the category.</td>
              </tr>
            <% end %>
              </tbody>
            </table>
    </div>
</div>